### ISSUE TITLE
Commenting on pull requests doesn't work

### ISSUE THREAD

**Issue by DStewart1997** [gitskarios/Gitskarios#245]
When leaving a comment on a pull request after posting it nothing happens.

Below comment suggests the issue doesn't affect comments on Issues.

Device: Sony Xperia Z3
Android Version: 5.1.1

**Comment by DStewart1997** [comment]
Test comment from app.

**Comment by miigotu** [comment]
@alorma I'd like to extend on this report, as it doesn't seem to completely describe the problem I've had since google changed their privacy settings for organizations a few weeks ago....

I am an admin for http://github.com/SiCKRAGETV

For about 2-3 weeks or so I have been unable to use gitskarios at all because I cannot open/close issues or pull requests, comment on issues or pull requests, or merge pull requests from the app. It simply says "merge failed" in the bottom or whatever the attempted action was.

The only thing I have been able to do really is get notifications and mark them as read.

**Comment by alorma** [comment]
It looks like they are changing something about organization permissions, i will fix it

**Comment by miigotu** [comment]
Yeah, we also had problems with out travis builds just after they changed the privacy stuff, guessing the permissions changed around the same time.

I'm always on here so just mention me if you need me to test the fixes before rolling it out. (preferably the apk because I dont have the time to figure out how to get the signing stuff working to compile =P)
