### ISSUE TITLE
proposition f-droid

### ISSUE THREAD

**Issue by azlux** [gitskarios/Gitskarios#433]
Hi,
Is it possible to put this app on F-droid ?

Azlux

**Comment by alorma** [comment]
`For software to be FOSS, the software in its entirety must be so - including all libraries and dependencies used. Additionally, it must be buildable with only FOSS tools.`

So, as far as i know, it cannot be built into F-Droid because i use Google Play Services to build the app.

I will think about F-Droid, but... what's the benefit about it?

**Comment by azlux** [comment]
benefit ? Having it on another platform. F-droid means open-source , so if an app is here it's mean a lot of things. For example I search on f-droid before google play when I need something.
Some apps on f-droid have non-free assets. I don't know how it's work with Google Play Service.
