### ISSUE TITLE
Events/organizations for wrong user displayed

### ISSUE THREAD

**Issue by nv-vn** [gitskarios/Gitskarios#530]
Here is what I see from the App: ![](http://i.imgur.com/NikIKLl.png)
But my feed looks like this on the Github website: ![](http://image.prntscr.com/image/bdc35f3fd0aa412c9257dfd35ba33dcc.png)

**Comment by nv-vn** [comment]
Events don't correspond to followers anymore: ,![](http://i.imgur.com/NikIKLl.png)

**Comment by GeorgeWL** [comment]
Can you tell us a bit of details?

like is it always happening or only under certain circumstances?

and of course:

Android Version:
Handset:
Gitskarios Version: 

_(found in the drawer under about, at the top under the logo)_

**Comment by nv-vn** [comment]
Always happens and it's always the same people/repositories who show up.

Android Version: 6.0.1
Phone: LG G5
App Version: 3.1.1, but it's been happening for at least 2-3 versions before this

**Comment by nv-vn** [comment]
Update on this: just installed the newest version of the app. Now on the sidebar I see more users or organizations [1]. I have no idea where these came from and I've never been involved with any of them. The one thing I notice here is that https://github.com/NV is a member of these specific organizations. He also often shows up on the events page on the app. Since my username is `nv-vn`, this makes me think that somewhere in either the app itself or in the Github API, my username is being parsed incorrectly (being cut off at the dash) and replaced with his username. In fact, if you look at the original screenshot on this issue, all the people on that page are people he follows. However, this seems weird since the app normally gets the username right (for example, I can post things from my own account or view my own "events" feed by going to my profile directly and looking at the events tab...).

[1]:<img src="http://i.imgur.com/vTZZQmr.png" width=180 height=320>

**Comment by nv-vn** [comment]
A quick code search for `.split("-")` brought me to [this file](https://github.com/gitskarios/Gitskarios/blob/6b4d43f73c1a5221ed0bbff1bd09c3f941a8fb3a/app/src/main/java/com/alorma/github/utils/AccountUtils.java). Indeed this does seem to be the issue here. However, it's weird that this works correctly in some places but not others. If this is not part of the Github API, perhaps it would be better to use a different character than `-` here, since that's a valid character in Github usernames (whereas `#` or `@` are not). Otherwise, just making sure that it only splits at the dashes that have been added on should fix this issue (although that seems like a more fragile solution).

**Comment by nv-vn** [comment]
Sorry to bother you, but @FarbodSalamat-Zadeh I saw you made created another Issue on this repository. Since you also have a dash in your username, would you mind confirming if you experience a similar bug? Since there's no user for https://github.com/FarbodSalamat I would expect you to see no events or organizations at all on your end.

**Comment by farbodsz** [comment]
Yeah of course, @nv-vn ,

My Events page is loading forever (with nothing except an indeterminate progress animation), so I'm guessing it's related to the aforementioned issue.

I've also spotted that the in the navigation menu, looking at the texts under the profile icon, the first shows "FarbodSalamat" and the second shows "Farbod Salamat-Zadeh".

This confims the issue with `.split("-")` because my username is "FarbodSalamat-Zadeh" (as you mentioned), but my actual name "Farbod Salamat-Zadeh" is displayed on the second line correctly.

I would completely agree that a different character should be used instead of `-` - one that isn't a valid character in GitHub usernames. Since changing this would be affecting a lot of the app (and would require significant refactoring, I'm assuming), this may be something @alorma can quickly fix as he is most familiar with the repository code.

**Comment by nv-vn** [comment]
Thanks for replying :) Looking back at the screenshot I posted, my name is indeed displayed as "nv" there. (I didn't notice because that's my username on most websites other than Github).

Anyways, some other characters that could be used in place of `-` here include: `_`, `.`, and `/` (which I think is probably the best since it's the least likely to become a valid character in usernames and `@` or `#` seem to carry their own semantic connotations).

**Comment by alorma** [comment]
hey! Great investigation! Thanks!!

I will fix it today soon, but the `-` problem is about a issue on N developer preview, so i assume it's not happening anymore as Nougat is released :)

**Comment by farbodsz** [comment]
Thanks for your reply, @alorma .

But I'm slightly confused - do you mean that the problem on the N developer preview is affecting the other versions of Android? ;) _Edit: Or after rereading, do you mean that the problem was occurring in all Android versions up to N developer preview, and so it does not occur on Nougat?_

The reason I say this is that @nv-vn stated he was using Android 6.0.1 (Marshmallow) and I was using 5.0.something (not sure of the specific version now) (Lollipop).

**Comment by alorma** [comment]
no, the think was i patched the problem adding a UUID to username, and now i see it was a bad idea :p

Anyway, i plan to refactor the account system from scratch, so not use android accounts anymore.

**Comment by nv-vn** [comment]
Awesome! Thanks for responding so fast/taking care of this!

**Comment by alorma** [comment]
Fixed! Will release soon!

**Comment by nv-vn** [comment]
Awesome! Thanks for your support :)
